# Generated by Django 5.2.8 on 2025-11-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
